### ISSUE TITLE
Changing locale dynamically

### ISSUE THREAD

**Issue by yoldar** [MikaelEdebro/vue-airbnb-style-datepicker#5]
Hi! First of all, thank you for that great calendar. Could please add to next releases dynamic locale change? Thanks you!

**Comment by MikaelEdebro** [comment]
I'll investigate if there's a good way of doing this. It seems that date-fns doesn't support locales with the CDN version.

What exactly is it that you're missing? I mean, you can just define your month/day names when instantiating the plugin. 
https://mikaeledebro.gitbooks.io/vue-airbnb-style-datepicker/INSTALLATION.html#plugin-options

And for displaying the date, vue-airbnb-style-datepicker doesn't restrict you to any specific formatting.

**Comment by yoldar** [comment]
I mean when user change locale you need to refresh whole VueJS app to change locale. Because you pass month/day names when VueJS inits. But goal is to pass locale as props.

P.s. This is not a problem anymore. I forked and did some customization :)

**Comment by henriollik** [comment]
Hi! I must admit, I have the same problem. With the current approach, application language can not be changed dynamically. For example, when translations are queried from the back-end, we can't update the application without losing state.

Translations should be a prop instead of a component option. Same for `sundayFirst` I would think.

The fork that @yoldar made, effectively makes the translations dynamically usable. Consider merging this functionality.

**Comment by papertokyo** [comment]
+1 for having translations as a prop. Any app that has multiple languages (e.g. a hotel website) needs to set the locale dynamically based on state, and shouldn't require a complete refresh.

**Comment by henriollik** [comment]
@MikaelEdebro Have you had the time to review yoldar's changes in his fork? It's a missing feature and people want it, please consider incorporating it into your project.

**Comment by abrantes01** [comment]
Do we have any news on this ? I'm facing the same problem. Maybe we could reopen the issue ?
