### ISSUE TITLE
Support for Date-Fns Version 2

### ISSUE THREAD

**Issue by ThomasRalee** [MikaelEdebro/vue-airbnb-style-datepicker#94]
Will there be support for `Date-Fns` Version **2**? 
Or maybe make this a configurable option?

**Comment by MikaelEdebro** [comment]
Yes I'm planning on making this compatible with date-fns 2. However, at current time it's only in Alpha. I think I will wait until at least Beta (or even official release), so the API:s are stable.

The issue is that they have changed the paths of their imports (from sub_months to subMonths), without adding backwards compatibility.
I made an issue there suggesting that they should add folders with the old name, just containing an index.js to the new module, but I don't think they were that interested.

**Comment by MikaelEdebro** [comment]
#57

**Comment by MikaelEdebro** [comment]
#57

**Comment by ThomasRalee** [comment]
Beta is in - https://github.com/date-fns/date-fns/releases/tag/v2.0.0-beta.3. @MikaelEdebro

**Comment by bnd170** [comment]
Would be nice to add support for `date-fns@2.0.0` now :)

Btw, amazing component @MikaelEdebro congratz!
